### ISSUE TITLE
WD should set the content type of the response based on the service details

### ISSUE THREAD

**Issue by mattetti** [mattetti/wd-sinatra#14]
Currently the content type isn't automatically set, but it should. Using a sinatra filter should be fine to do that.

**Comment by mattetti** [comment]
I've been thinking about this one for a while and I'm kind of bothered by automatically setting the content type because WD currently allows you to set multiple types. 

Here is what I personally do in `hooks.rb`:

```
def pre_dispatch_hook
    content_type 'application/json', :charset => 'utf-8' if service.formats.include?(:json)
```

So by default I set the content type to json if the service supports json but it can be overwritten in the service implementation.

**Comment by kamui** [comment]
Shouldn't content_type also depend on the accept header? I've used [rack-accept](https://github.com/mjijackson/rack-accept) like this in a previous sinatra API app:

``` ruby
  require "rack/accept"
  SUPPORTED_MEDIA_TYPES = {
    "application/json" => :json,
    "application/xml" => :xml,
  }

  before do
    accept = env["rack-accept.request"]
    media_type = accept.media_type.best_of(SUPPORTED_MEDIA_TYPES.keys)
    halt 406 unless media_type
    content_type SUPPORTED_MEDIA_TYPES[media_type], charset: "utf-8"
  end
```

This example only supports app wide content_types, so it'd have to be modified to compare against the available service formats.

**Comment by kamui** [comment]
Took a stab at implementation [here](https://github.com/kamui/wd-sinatra/commit/5afb5f227ae24dbb6c28ddb9e5d5361c838a456d). I'm not sure about putting the format in `params`. 

`charset` is hardcoded to `utf8` too, this should probably be also negotiated between the `Accept` header `charset` and some service definition.

Maybe also use [Sinatra::RespondWith](http://www.sinatrarb.com/contrib/respond_with.html) to deal with returning different responses, as opposed to the switch statement I used is the `hello_world` service, or maybe leave it up to the user. If they use `rabl`  for instance, they might be able to just render a single rabl template for both json and xml.
