### ISSUE TITLE
No way to update an existing WD app when wd-sinatra is updated

### ISSUE THREAD

**Issue by aeden** [mattetti/wd-sinatra#15]
To clarify this is for cases where code is generated running wd_sinatra. You cannot rerun wd_sinatra on an existing WD app to update it and you should be able to (for example to get the awesome Thor integration for service generation)

**Comment by mattetti** [comment]
The way to upgrade is to generate the app on top of the existing one which will ask you if you want to replace the files that are differing and also show you a diff of the files in question.
I guess that isn't mentioned in the README or it's not clearly enough mentioned :(
- Matt (via a mobile device)

**Comment by mattetti** [comment]
just verified, it's in the documentation but at the bottom and could be made clearer.
