### ISSUE TITLE
add example to use template

### ISSUE THREAD

**Issue by gfrancesco** [mattetti/wd-sinatra#16]
Thanks for the great work, can you please give me a hint on how to integrate `Rabl` (https://github.com/nesquena/rabl)?
I've ActiveRecord running, but I'm quite stuck at adding templates/controllers.

thanks

**Comment by gfrancesco** [comment]
Found a way, just anybody needs `Rabl` with `ActiveRecord`:
- add `rabl` to your Gemfile
- add in `lib/app.rb`:

``` ruby
require 'rabl'
Rabl.register!
```
- as service implementation:

``` ruby
service.implementation do
  @foo = Car.find(params[:id])
  Rabl::Renderer.json(@foo, 'cars', view_path: 'views')
end
```
- put your `cars.rabl` template under `views/`

**Comment by mattetti** [comment]
Thanks for finding the solution and posting it here. I don't use Rabl but I'm glad to see you got it working.
