### ISSUE TITLE
Using SSL

### ISSUE THREAD

**Issue by cawel** [mattetti/wd-sinatra#19]
I need to have my API app under HTTPS. I guess I can use the 'rack/ssl-enforcer' middleware. But from what I understand, I also need to pass some options when starting the web server (Webrick, not Sinatra), like the certificate details or the SSLenable flag. 

But I can't find the place where the `WEBrick::HTTPServer.new` call is made. Or is there an even simpler way I could do it?

**Comment by mattetti** [comment]
SSL is usually handled by nginx, apache or whatever web server you use. Sinatra will use whatever Ruby server you have installed or specified (by default it starts WEBrick but you really shouldn't use that in prod).

Let say you use Puma, to start your WD app using SSL:

```
$ cd my_app
$ puma -b tcp://0.0.0.0:8080 -b ssl://0.0.0.0:8443?key=./ssl/matt.key&cert=./ssl/matt.crt
```

To generate self signed certs:

```
$ openssl genrsa -des3 -out matt.key 1024
$ openssl req -new -key server.key -out matt.csr
$ openssl x509 -req -days 365 -in server.csr -signkey 
mattt.key -out matt.crt
```

Thin also does support setting SSL certs. But as I said, in most cases, you will do that at the webserver level (Nginx/Apache/whatever).

I hope it helps.

**Comment by cawel** [comment]
It does help, thanks. Using Thin as a web server, it's also very simple to work in development: 

```
bundle exec thin --ssl start
```
