### ISSUE TITLE
DataMapper in place of ActiveRecord

### ISSUE THREAD

**Issue by theCrab** [mattetti/wd-sinatra#20]
Just starting on a personal project that I hope to have a mobile app for. 

Could you give me some hints on how to get **DataMapper** to play the drums, while **Sinatra** performs on this _WD World Tour 2013_?

Thanks.

**Comment by theCrab** [comment]
I tried this but am not sure if am loading the models properly.

``` ruby
# file: lib/app.rb

# called after the environment is setup and the basic dependencies are loaded
# but before the models are loaded.
#
# Here you want to load your dependencies and maybe set your
# datastore.
require "datamapper"
# 
####### formatting the timestamps for JS ############
class Time; def to_json(*a); iso8601.to_json(*a); end; end
# 
# Log
DataMapper::Loger.new($stdout, :debug)
# 
# establish db connection
DataMapper.setup(:default, {
  :adapter  => 'sqlite3',
  :database => "db/#{ENV['RACK_ENV']}.sqlite3"
  # ,
  # :username => 'username',
  # :password => 'password',
  # :host     => 'hostname'
  })

# 
# load the models
Dir.glob("./models/*.rb") { |file| require "#{file}" }
# 
# prepare the database and validate the models
DataMapper.finalize
# 
# run models against the db
DataMapper.auto_upgrade! # this is safe for production
# DataMapper.auto_migrate! # this is only good for test/development. It wipes the database everytime it runs.

...
```

**Comment by mattetti** [comment]
So technically you don't need to load the models, they are already model as part of the bootloader: https://github.com/mattetti/wd-sinatra/blob/master/lib/wd_sinatra/app_loader.rb#L28
(they get loaded after the `app.rb` file so you can set the ORM.

Here is the boot order based the file linked above:

``` ruby
        set_env
        set_loadpath
        load_environment
        load_lib_dependencies
        load_app_file
        load_models
        load_apis
# if server mode
        load_middleware
        set_sinatra_routes
        set_sinatra_settings
        load_hooks
```

But it seems that in the case of DM, you need to `#finalize` & `#auto_upgrade!` after loading the models which I lack a hook for. Something we could do, would be to add a hook for `after_models_loaded` which would take an array of blocks to execute after running https://github.com/mattetti/wd-sinatra/blob/master/lib/wd_sinatra/app_loader.rb#L95 

What do you think?
