### ISSUE TITLE
WD-Sinatra and Spree API

### ISSUE THREAD

**Issue by theCrab** [mattetti/wd-sinatra#25]
Hi
(May not be an Issue) **My apologies in advance**, this is partly related to WD and Spree. I am looking for ideas and tips on implementation.

So I have been given an assignment to make a til/terminal/POS for a shop. There are multiple tils used by different shop attendants at the same time. 

This is a physical shop running on Spree Commerce V1.3.2-stable. Spree comes with their API and I would like to use that to search and insert line_items into the Order at the Cart level and proceed to place the order.

As WD is used to build API's, how if possible could I accomplish this feat. Give me some ideas. I code alone and sometimes I hit the wall mentally like now. 

Thanks

**Comment by mattetti** [comment]
This is definitely not an issue but a question ;) I'll close it but let's still discuss your use case.

I'm familiar with POS solutions but not with Spree. Are you trying to add an API to Spree or do you need to add another API that will be used from Spree?
