### ISSUE TITLE
Using wd-sinatra with sidekiq

### ISSUE THREAD

**Issue by fellix** [mattetti/wd-sinatra#31]
This is not really an issue, but I've an application which uses wd-sinatra, and now I want to use some workers here.

Sidekiq requires an option to load all the environment (using the option -r), usually, in a sinatra application, that file will be the app.rb or application.rb (or whatever the name you picked).

Since the config.ru on wd-sinatra loads the weasel environment and inject it into Sinatra, I cannot refer to any of my files to load the sidekiq correctly.

I tried to generate my own app.rb, and it was like these:

``` ruby
class App < Sintra::Base
  configure do
     root = File.expand_path(File.dirname(__FILE__))
     WDSinatra::AppLoader.server(root)
  end
end
```

then I just ran on config.ru file this app, Sidekiq have worked, but any call to my endpoints became missing, like the WDSinatra::AppLoader do not have any effect.

Do you guys have any idea how i can fix this?
- Sorry for posting this like an issue, I looked for a google group, but I do not found one *

**Comment by kamui** [comment]
Try putting this in a ruby file (like `lib/console.rb`) and loading it with sidekiq:

``` ruby
require 'bundler'
Bundler.setup
require 'wd_sinatra/app_loader'
root = File.expand_path('..', File.dirname(__FILE__))
WDSinatra::AppLoader.console(root)
```

In `Procfile`:

``` ruby
worker:    bundle exec sidekiq -r ./lib/console.rb
```

`AppLoader.console` will load the environment, models, app file, api route classes, but won't set the routes in sinatra or middleware.rb.

**Comment by fellix** [comment]
@kamui you are amazing

worked like magic, thank you very much
