### ISSUE TITLE
Doc generator ignores closing ul tag in _input_params.erb

### ISSUE THREAD

**Issue by kamui** [mattetti/wd-sinatra#36]
I'm trying to add optional namespace support into the doc generator in wd_sinatra, but I'm running into an existing bug. In _input_params.erb, the entire template is wrapped in a ul tag. For some reason, the closing ul tag is being ignored by ERB. When the document is rendered with multiple namespaces, the namespaces get nested into each other because the ul tag isn't rendered. Here's a screenshot:

http://cl.ly/Qyvm/Screen%20Shot%202013-08-22%20at%207.47.10%20PM.png

Here's the input:

``` ruby
  service.params do |p|
    p.string  :name, :default => 'World'

    p.namespace :user do |user|
      user.string :ssn, :required => true
    end

    p.namespace :attachment, :null => true do |attachment|
      attachment.string :url, :required => true
      attachment.string :type, :required => true
    end
  end 
```

I'm using ruby 2.0.0-p247, but I haven't been able to figure out why this is happening.

**Comment by kamui** [comment]
@raul Since you wrote that bit, I wondered if you've been experiencing this weirdness as well.

**Comment by kamui** [comment]
Turns out it was the comment that was preventing the ul from rendering.

**Comment by raul** [comment]
Good catch @kamui!
